// Generated by CoffeeScript 1.7.1
(function() {
  var Background;

  Background = (function() {
    function Background() {
      $((function(_this) {
        return function() {
          return _this.init();
        };
      })(this));
    }

    Background.prototype.init = function() {
      console.log('Initializing..');
      return this.startCapture();
    };

    Background.prototype.startCapture = function() {
      var embedDiv, embedString;
      embedString = '<embed width=0 height=0 src="pnacl/manifest.nmf" ps_tty_prefix="ps:" ps_stdout="/dev/tty" ps_stderr="/dev/tty" type="application/x-nacl" />';
      embedDiv = $('<div />').appendTo('body');
      embedDiv[0].addEventListener('load', (function(_this) {
        return function() {
          return _this.handleLoad();
        };
      })(this));
      embedDiv.on('load', (function(_this) {
        return function() {
          return _this.handleLoad();
        };
      })(this));
      embedDiv[0].addEventListener('error', (function(_this) {
        return function() {
          return _this.handleError();
        };
      })(this));
      embedDiv.on('error', (function(_this) {
        return function() {
          return _this.handleError();
        };
      })(this));
      embedDiv[0].addEventListener('message', (function(_this) {
        return function() {
          return _this.handleMessage();
        };
      })(this));
      embedDiv.on('message', (function(_this) {
        return function() {
          return _this.handleMessage();
        };
      })(this));
      return embedDiv.html(embedString);
    };

    Background.prototype.handleLoad = function() {
      return console.log('Loaded!!');
    };

    Background.prototype.handleError = function() {
      return console.log('Error!!');
    };

    Background.prototype.handleMessage = function() {
      return console.log('Message!!');
    };

    return Background;

  })();

  new Background();


  /*chrome.app.runtime.onLaunched.addListener(function(launchData) {
    alert('opened');
  });
  
  chrome.runtime.onInstalled.addListener(function() {
    console.log('installed');
  });
  
  chrome.runtime.onSuspend.addListener(function() { 
    // Do some simple clean-up tasks.
  });
   */

}).call(this);
